### ISSUE TITLE
add 90th, 95th and 99th percentile

### ISSUE THREAD

**Issue by derhuerst** [56quarters/staccato#21]
staccato currently prints the median (a.k.a. 2nd quartile a.k.a. 50th [percentile](https://en.wikipedia.org/wiki/Percentile)). For latency statistics, the "shape" of the "long tail" is often very relevant, so I propose to print the 90th, 95th and 99th percentile as well.

**Comment by 56quarters** [comment]
Hi @derhuerst ,

Staccato can currently print 90th, 95th, etc percentiles via a CLI flag (`-p` or `--percentiles`). Does this meet your usecase? Or are you looking for the 90th, 95th, etc percentiles to be output by default when no extra `-p` arguments are provided?

```
$ ./target/debug/st -p 90,95,99 benches/values-large.log 
count: 100000
sum: 31267.88217
mean: 0.31268
upper: 15.39197
lower: 0.00252
median: 0.02942
stddev: 0.90941
count_90: 90000
sum_90: 7668.58249
mean_90: 0.08521
upper_90: 0.77555
lower_90: 0.00252
median_90: 0.02228
stddev_90: 0.15327
count_95: 95000
sum_95: 13602.94400
mean_95: 0.14319
upper_95: 1.66425
lower_95: 0.00252
median_95: 0.02560
stddev_95: 0.29331
count_99: 99000
sum_99: 24396.58972
mean_99: 0.24643
upper_99: 4.74899
lower_99: 0.00252
median_99: 0.02851
stddev_99: 0.60246
```

**Comment by derhuerst** [comment]
> Staccato can currently print 90th, 95th, etc percentiles via a CLI flag (`-p` or `--percentiles`). Does this meet your usecase?

Yes! Missed that, sorry.

> Or are you looking for the 90th, 95th, etc percentiles to be output by default when no extra `-p` arguments are provided?

No. I'm just a random stranger from the internet who has just discovered this neat little tool, but this is my personal opinion:

- The level of detail shown in your previous comment should be (stay) opt-in.
- By default, `lower_95` & `upper_95` should be shown (in addition to the existing ones).

**Comment by 56quarters** [comment]
I think that's a good idea. Shouldn't be too hard to do, either.
